services:
  - type: web
    name: nholyn-portfolio
    runtime: node
    plan: free
    buildCommand: cd client && npm install --include=dev && npm run build && cd ../server && npm install
    startCommand: cd server && npm start
    autoDeploy: true
    domains:
      - nholyngrace.com
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        value: https://nholyngrace.com
      - key: ADMIN_USERNAME
        value: nholyn
      - key: ADMIN_PASSWORD_HASH
        value: $2b$12$fY9lzL2KPv4uhgjrdQsOCeyOUD79MYS4jGc2UBTs4SXYSi9HxNHI6
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
